### ISSUE TITLE
"example squid 3/4 configuration in ./examples."

### ISSUE THREAD

**Issue by westurner** [revsys/optimized-python-docker#1]
> Build times are radically reduced by using a local proxy. You can find an example squid 3/4 configuration in ./examples.

https://github.com/revsys/optimized-python-docker/blob/master/README.md

Where is the ./examples directory you speak of?

**Comment by frankwiles** [comment]
Doh sorry about that, just pushed it up in this commit https://github.com/revsys/optimized-python-docker/commit/51981bb0cabfe46fd9e70fdbbd2018a1c7144b02. 

Hope you're doing well!

**Comment by westurner** [comment]
Thanks!!
