### ISSUE TITLE
Pyenv

### ISSUE THREAD

**Issue by Guest007** [revsys/optimized-python-docker#3]
Will it be available on pyenv?

**Comment by frankwiles** [comment]
I'm not sure what you mean by that.  This is a Docker image, not something that is pyenv/pip installable.

**Comment by gladiatr72** [comment]
Hey there.  I know I have seen a formula for insighting pyenv to build optimized binaries--unfortunately I do not remember where!  Since this is, by definition, an already-built python environment, pyenv doesn't come into play.
