### ISSUE TITLE
Update to 3.6.4

### ISSUE THREAD

**Issue by jefftriplett** [revsys/optimized-python-docker#4]
Our Docker Hub registry has 3.6.4 images, but we didn't push the files here.

**Comment by gladiatr72** [comment]
There were some files missing from the original repository (revsys/docker-builds/python). I've merged them here. Until something changes with the way Python builds, Python version bumps don't require any changes on this end--the version is set with `PYTHON_VERSION=3.N.X` on the `make` CLI.
