### ISSUE TITLE
cannot build PYTHON_VERSION=3.7.0  --> gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by kbrown** [revsys/optimized-python-docker#7]
I know y'all pushed a revolutionsystems/python:3.7.0-wee-optimized-lto image to dockerhub but I can't reproduce the build with the code in this repo.

Details:

Winebook:optimized-python-docker kevin$ env
PYTHON_VERSION=3.7.0

docker build .

[...]

Step 11/44 : RUN    curl -L -o /python.tar.xz "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz"     && curl -L -o /python.tar.xz.asc "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz.asc"         && gpg --keyserver ha.pool.sks-keyservers.net --refresh-keys 2>&1 | egrep -v 'requesting key|not changed'         && gpg --batch --verify /python.tar.xz.asc /python.tar.xz         && mkdir -p /usr/src/python         && tar -xJC /usr/src/python --strip-components=1 -f /python.tar.xz
 ---> Running in 59c774495749
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0   1024      0 --:--:-- --:--:-- --:--:--  1031
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0   1034      0 --:--:-- --:--:-- --:--:--  1038
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: key CA57AD7C: invalid direct key signature removed
gpg: key CA57AD7C: invalid direct key signature removed
gpg: key CA57AD7C: "PGP Global Directory Verification Key" 2 signatures cleaned
gpg: Total number processed: 1
gpg:     signatures cleaned: 2
gpg: refreshing 21 keys from hkp://ha.pool.sks-keyservers.net
gpg: key AA65421D: "Ned Deily (Python release signing key) <nad@python.org>" 12 new signatures
gpg: key 18ADD4FF: "Benjamin Peterson <bp@benjamin.pe>" 3 new signatures
gpg: key 6F5E1540: "Ned Deily <nad@acm.org>" 2 new signatures
gpg: key CAC5C305: "Alex Vandiver <alex@chmrr.net>" 4 new signatures
gpg: key 8EFE0655: "Zev Benjamin <zev@strangersgate.com>" 4 new signatures
gpg: key A4135B38: "Benjamin Peterson <benjamin@python.org>" 1 new signature
gpg: key 830F6F7E: "Ernest W. Durbin III <ewdurbin@gmail.com>" 1 new user ID
gpg: key 830F6F7E: "Ernest W. Durbin III <ewdurbin@gmail.com>" 5 new signatures
gpg: key 498C1579: "Benjamin W. Smith (The Groundwork) <benjaminws@thegroundwork.com>" 4 new signatures
gpg: Total number processed: 21
gpg:              unchanged: 13
gpg:           new user IDs: 1
gpg:         new signatures: 35
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   3  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   3  signed:   6  trust: 3-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2018-09-21
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
The command '/bin/sh -c curl -L -o /python.tar.xz "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz"     && curl -L -o /python.tar.xz.asc "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz.asc"         && gpg --keyserver ha.pool.sks-keyservers.net --refresh-keys 2>&1 | egrep -v 'requesting key|not changed'         && gpg --batch --verify /python.tar.xz.asc /python.tar.xz         && mkdir -p /usr/src/python         && tar -xJC /usr/src/python --strip-components=1 -f /python.tar.xz' returned a non-zero code: 2

**Comment by frankwiles** [comment]
Ah probably a bug that didn't get pushed to the repo.  Thanks for reporting it to us! 

@gladiatr72 can you take a look at this in the near future?

**Comment by gladiatr72** [comment]
Ugh.  Near future---far future :)  On it.  Thank you for the report, @kbrown!

**Comment by gladiatr72** [comment]
@kbrown Hey there. Finally got a chance to look at this--what you were seeing was a failure looking up public gpg keys on the sks-keyserver.net key server.  It's f*g amazing in how it's a free service that is only slightly wobbly, but, alas, it is a _little_ wobbly.
